//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTS_Int
    {
        public int Key { get; set; }
        public int Rank { get; set; }
        public string Query { get; set; }
    }
}
